import { chromium } from '@playwright/test'
const browser = await chromium.launch()
for (const theme of ['sakura', 'forest', 'mono']) {
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, locale: 'zh-CN' })
  const page = await ctx.newPage()
  await page.addInitScript((t) => localStorage.setItem('activation-manager-theme', t), theme)
  await page.goto('http://127.0.0.1:3400/admin/login')
  await page.locator('#username').fill('admin')
  await page.locator('#password').fill('123456')
  await page.getByRole('button', { name: '登录后台' }).click()
  await page.waitForURL(/\/admin\/overview/, { timeout: 30000 })
  await page.goto('http://127.0.0.1:3400/admin/settings?section=branding', { waitUntil: 'networkidle' }).catch(() => {})
  await page.waitForTimeout(600)
  await page.screenshot({ path: `/tmp/theme-shots/${theme}-settings-section.png` })
  await page.goto('http://127.0.0.1:3400/admin/licenses', { waitUntil: 'networkidle' }).catch(() => {})
  await page.waitForTimeout(600)
  await page.screenshot({ path: `/tmp/theme-shots/${theme}-licenses.png` })
  await page.goto('http://127.0.0.1:3400/admin/login', { waitUntil: 'networkidle' }).catch(() => {})
  await page.evaluate(() => fetch('/api/admin/logout', { method: 'POST' }).catch(() => {}))
  await page.waitForTimeout(300)
  await ctx.close()
}
await browser.close()
console.log('shots done')
